recommit
HEIGE-PCloud/DoIt pull request #21
Opened 2021-04-25 10:48 UTC by SpongeBab

update README.md.Fix profile images.

2021-04-25 11:34 UTC, HEIGE-PCloud commented
为什么需要新增这张图片？`assets/images/avatar.png`

2021-04-25 11:45 UTC, HEIGE-PCloud requested changes
1. 不需要新增avatar。原有的avatar保存在`/exampleSite/assets/images/avatar.png`。主题内并不需要内置这张avatar，用户应该自行设置自己的图片。
2. `Install`标题应该使用h2 tag `##` 而非 h1 tag `#`。
3. 我倾向于将安装指南拆分成两部分，“get started” 和 “migrate from LoveIt”。
4. 需要使用更流畅自然的描述性语句。“强烈建议”应修改为“应该”或“需要”。“否则你会无法使用该主题”，意义不明。
5. 我会提交一个commit来修复上述问题。

2021-04-25 12:10 UTC, HEIGE-PCloud submitted a review, later dismissed

2021-04-25 12:50 UTC, SpongeBab commented
> * 不需要新增avatar。原有的avatar保存在`/exampleSite/assets/images/avatar.png`。主题内并不需要内置这张avatar，用户应该自行设置自己的图片。
> * `Install`标题应该使用h2 tag `##` 而非 h1 tag `#`。
> * 我倾向于将安装指南拆分成两部分，“get started” 和 “migrate from LoveIt”。
> * 需要使用更流畅自然的描述性语句。“强烈建议”应修改为“应该”或“需要”。“否则你会无法使用该主题”，意义不明。
> * 我会提交一个commit来修复上述问题。

是这样的。因为我尝试了你的方法。在exampleSite生成过程中出现了问题。如果你想要更具体的信息。我明天尝试复现一下。但是我不知道能否复现。
我决定直接使用hugo server去开发网站。当我将图片放在asset/images/下，它立刻生效了。当我放在其他任何地方，都没有效果。
如果放在这里，可以直接使用Loveit的toml配置复现成功。

2021-04-25 14:53 UTC, HEIGE-PCloud commented
我按照 https://hugodoit.pages.dev/theme-documentation-basics/ 尝试复现你遇到的问题。

![image](https://user-images.githubusercontent.com/52968553/115997217-47251c00-a5da-11eb-9651-b83aa6611df6.png)

这是我遇到的页面。如果你遇到的是这样的页面，可以称为预期行为，因为用于并没有配置自己的头像。他们应该注意到这一点，并去修改`[params.home.profile]`中的选项。如果在主题中配置了默认的头像，确实可以fallback到默认头像。但这会给用户造成困惑。他们会发现默认的`avatarURL = "/images/avatar.png"`并试着寻找这张图片，然后在主题的目录下寻找到这张图片。这可能会误导他们并让他们将新的图片与资源放置在`themes`目录下。

我认为更好的方法是在[说明文档](https://hugodoit.pages.dev/theme-documentation-basics/)中给出更明确的说明和链接，并在`config.toml`的配置项上下文中添加一些额外的说明，并保留这个无法加载的行为，让用于有意识地阅读并在正确的位置添加头像。

2021-04-25 15:24 UTC, HEIGE-PCloud commented
我添加了头像配置的相关描述，可以在这里查看[英文](https://d774dd04.hugodoit.pages.dev/theme-documentation-basics/#site-configuration)与[中文](https://d774dd04.hugodoit.pages.dev/zh-cn/theme-documentation-basics/#site-configuration)的关于头像配置技巧的文档。

2021-04-25 19:23 UTC, HEIGE-PCloud submitted a review, later dismissed

2021-04-25 23:19 UTC, SpongeBab commented
是的，你所展示的正是我遇到的问题。
如果这样是正常的，我们必须在config.toml的头像配置部分添加说明，以便让使用的人知道这是正常现象。或者在README中添加一张demo。毕竟在原版的LoveIt主题不会出现此现象。
不过我建议保留此图片，这会改善用户体验。只需要提醒用户头像图片路径是不同于其他图片路径的。并且让用户自己决定是否更换头像。

2021-04-26 07:04 UTC, HEIGE-PCloud commented
> 毕竟在原版的LoveIt主题不会出现此现象。

![image](https://user-images.githubusercontent.com/52968553/116042001-d4618280-a665-11eb-9701-a1234bf6a011.png)

在LoveIt中也复现了这个问题。

> 不过我建议保留此图片，这会改善用户体验。只需要提醒用户头像图片路径是不同于其他图片路径的。并且让用户自己决定是否更换头像。

我同意保留这张默认图片。

2021-04-26 16:42 UTC, HEIGE-PCloud approved these changes

2021-04-27 07:40 UTC, merged