[Feature] Add remark42 comment system support
HEIGE-PCloud/DoIt pull request #239
Opened 2021-09-24 21:34 UTC by HEIGE-PCloud

- Update comment.html and config.toml for related configs
- Update documentation and READMEs
- Update theme.js

(#236)

2021-09-24 21:39 UTC, HEIGE-PCloud commented
@xqbumu 麻烦帮忙测试一下是否工作正常 🤔

2021-09-25 08:47 UTC, xqbumu commented
> @xqbumu 麻烦帮忙测试一下是否工作正常 🤔

好的，收到

2021-09-25 10:51 UTC, xqbumu requested changes

2021-09-25 10:51 UTC, xqbumu commented on src/js/theme.js
> +            };
第768行后也许要加上
```js
window.remark_config = remark_config;
```
以使remark42 的 /web/embed.mjs 不至于报错，但是不够优雅；
当然也可以在 remark42 端进行报错兼容。

2021-09-25 12:40 UTC, HEIGE-PCloud commented on src/js/theme.js
> +            };
改完了，再试试看？

2021-09-25 13:28 UTC, xqbumu approved these changes
本地测试能正常工作了，谢谢🙏

2021-09-25 13:29 UTC, merged