feat: Social add QQ and QQGroup support
HEIGE-PCloud/DoIt pull request #256
Opened 2021-09-30 06:13 UTC by gclm

2021-09-30 12:49 UTC, HEIGE-PCloud requested changes

2021-09-30 12:49 UTC, HEIGE-PCloud commented on assets/data/social.yml
> +    Src: svg/icons/qqGroup.svg
没有配置链接只有一个图标有啥用？

2021-09-30 12:51 UTC, HEIGE-PCloud commented on assets/data/social.yml
> +    Src: svg/icons/qqGroup.svg
可以通过设置 `Template` 或者 `Prefix` 的属性来配置跳转链接，我对于 QQ 的接口不怎么熟悉，麻烦你修改一下。

2021-10-01 02:04 UTC, gclm commented on assets/data/social.yml
> +    Src: svg/icons/qqGroup.svg
目前配置链接发现不太行，也有可能我对这个模板不太熟悉
**协议示例**
- QQ = "https://sighttp.qq.com/authd?IDKEY=a84eb18af0b8670c97bfd27e47b731f28c9760c2d772a39f"
- QQGroup = "https://qm.qq.com/cgi-bin/qm/qr?k=cNZQ_5Il1FNVYMP_XhCqrAlks8K7_6WQ&jump_from=webapi"

**配置方案**

>以QQ为例
- Prefix: https://sighttp.qq.com/authd?IDKEY= --> 拼出来的url： https://sighttp.qq.com/authd?IDKEY=/a84eb18af0b8670c97bfd27e47b731f28c9760c2d772a39f --> 多一个/
- Prefix: https://sighttp.qq.com/authd?IDKEY=%v --> 拼出来的url: https://sighttp.qq.com/authd?IDKEY=a84eb18af0b8670c97bfd27e47b731f28c9760c2d772a39f/%25!v%28MISSING%29  --> 多一 **个/%25!v%28MISSING%29**

2021-10-02 11:07 UTC, HEIGE-PCloud commented
@gclm 我做了一些修改，麻烦你测试一下这样是否可行？

2021-10-03 10:26 UTC, HEIGE-PCloud approved these changes

2021-10-03 10:31 UTC, merged

2021-10-05 12:43 UTC, gclm commented
@HEIGE-PCloud 不好意思，这几天在外面没电脑没进行测试，我已经查看过你的修改了发现不行，情况我以前评论的一样，
![image](https://user-images.githubusercontent.com/27618687/136024650-c0e3cc8b-a1ec-4c54-99f2-aac08d8521d1.png)

2021-10-05 13:04 UTC, HEIGE-PCloud commented
抱歉 没有注意到 `/` 的问题，我已经在最新的 commit 中提交了一个修复，麻烦你更新到最新的 commit 看一下这个问题是否被修复？

2021-10-05 13:52 UTC, gclm commented
已经测试过了。QQGroup 预计需要修改成这个**Template: https://qm.qq.com/cgi-bin/qm/qr?k=%v&jump_from=webapi**
![image](https://user-images.githubusercontent.com/27618687/136036442-3f3d263b-1304-433d-8fc9-61230e476ba7.png)