feat: add multi authors support
HEIGE-PCloud/DoIt pull request #98
Opened 2021-06-07 00:15 UTC by xqbumu

feat: add multi authors
feat(authors): add link
docs: add authors

with feature: #96

2021-06-07 07:50 UTC, HEIGE-PCloud requested changes
The author field in RSS file is not updated.

For example, in `/categories/tests/index.xml`

```
<item>
<title>Author single test</title>
<link>http://localhost:1313/author-single-tests/</link>
<pubDate>Mon, 07 Jun 2021 08:46:10 +0100</pubDate>
<author>PCloud</author>
<guid>http://localhost:1313/author-single-tests/</guid>
<description>
<![CDATA[ <p>Just for authors test.</p> ]]>
</description>
</item>
```

Items have incorrect author.

2021-06-07 09:23 UTC, xqbumu commented
> 
> 
> The author field in RSS file is not updated.
> 
> For example, in `/categories/tests/index.xml`
> 
> ```
> <item>
> <title>Author single test</title>
> <link>http://localhost:1313/author-single-tests/</link>
> <pubDate>Mon, 07 Jun 2021 08:46:10 +0100</pubDate>
> <author>PCloud</author>
> <guid>http://localhost:1313/author-single-tests/</guid>
> <description>
> <![CDATA[ <p>Just for authors test.</p> ]]>
> </description>
> </item>
> ```
> 
> Items have incorrect author.

多作者的情况下rss该怎么处理，当时没的搜到相关内容，所以就按默认的处理了，你这样有了解相关的东西吗？

2021-06-07 09:58 UTC, HEIGE-PCloud commented
> > The author field in RSS file is not updated.
> > For example, in `/categories/tests/index.xml`
> > ```
> > <item>
> > <title>Author single test</title>
> > <link>http://localhost:1313/author-single-tests/</link>
> > <pubDate>Mon, 07 Jun 2021 08:46:10 +0100</pubDate>
> > <author>PCloud</author>
> > <guid>http://localhost:1313/author-single-tests/</guid>
> > <description>
> > <![CDATA[ <p>Just for authors test.</p> ]]>
> > </description>
> > </item>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Items have incorrect author.
> 
> 多作者的情况下rss该怎么处理，当时没的搜到相关内容，所以就按默认的处理了，你这样有了解相关的东西吗？
> 
> 晚点我再研究下。
> 
> 或者以 author 作为第一优先级，不存在则取第一个authors，最后取 config的作者。
> 
> 或者以
> 
> ```
> <author>author1@example.org (author1), author2@example.org (author2)</author>
> ```
> 
> 方式处理。

RSS 标准中本不包含 `<author>` 字段，但大多数阅读器都对 `<author>` 有支持，但支持的程度不同。我倾向于遵守 [Atom 1.0](https://datatracker.ietf.org/doc/html/rfc4287) 的标准来处理 `<author>`。当有多个作者时，按照以下格式处理。

```
<author>
    <name>Author 1</name>
    <uri>http://example.org/</uri>
    <email>author1@example.com</email>
</author>
<author>
    <name>Author 2</name>
    <uri>http://example.org/</uri>
    <email>author2@example.com</email>
</author>
```
但不同阅读器可能对于这个格式会有不同的处理方式，可能只显示第一个或最后一个，这个就交给用户和阅读器来做选择了。

2021-06-07 10:01 UTC, xqbumu commented
> 
> 
> > > The author field in RSS file is not updated.
> > > For example, in `/categories/tests/index.xml`
> > > ```
> > > <item>
> > > <title>Author single test</title>
> > > <link>http://localhost:1313/author-single-tests/</link>
> > > <pubDate>Mon, 07 Jun 2021 08:46:10 +0100</pubDate>
> > > <author>PCloud</author>
> > > <guid>http://localhost:1313/author-single-tests/</guid>
> > > <description>
> > > <![CDATA[ <p>Just for authors test.</p> ]]>
> > > </description>
> > > </item>
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Items have incorrect author.
> > 
> > 
> > 多作者的情况下rss该怎么处理，当时没的搜到相关内容，所以就按默认的处理了，你这样有了解相关的东西吗？
> > 晚点我再研究下。
> > 或者以 author 作为第一优先级，不存在则取第一个authors，最后取 config的作者。
> > 或者以
> > ```
> > <author>author1@example.org (author1), author2@example.org (author2)</author>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 方式处理。
> 
> RSS 标准中本不包含 `<author>` 字段，但大多数阅读器都对 `<author>` 有支持，但支持的程度不同。我倾向于遵守 [Atom 1.0](https://datatracker.ietf.org/doc/html/rfc4287) 的标准来处理 `<author>`。当有多个作者时，按照以下格式处理。
> 
> ```
> <author>
>     <name>Author 1</name>
>     <uri>http://example.org/</uri>
>     <email>author1@example.com</email>
> </author>
> <author>
>     <name>Author 2</name>
>     <uri>http://example.org/</uri>
>     <email>author2@example.com</email>
> </author>
> ```
> 
> 但不同阅读器可能对于这个格式会有不同的处理方式，可能只显示第一个或最后一个，这个就交给用户和阅读器来做选择了。

好的

2021-06-07 10:30 UTC, HEIGE-PCloud reviewed
是否可以统一将 author 页面的 `RelPermalink` 设置为作者的 id？

2021-06-07 10:30 UTC, HEIGE-PCloud commented on exampleSite/data/authors/PCloud.toml
> +
我创建了一个新的 test case，它拥有相同的包含大小写字符的 `id` 和 `name.display`。

2021-06-07 10:30 UTC, HEIGE-PCloud commented on layouts/taxonomy/terms.html
> +                                <a href="{{ .RelPermalink }}">
此时，作者 PCloud 的 author 页面的 `{{ .RelPermalink }}` 为 `/authors/pcloud/`。

2021-06-07 10:30 UTC, HEIGE-PCloud commented on layouts/partials/meta/author.html
> +            <a href='{{ .link }}'>{{- .name -}}</a>
然而此时 `{{ .link }}` 的值为 `/authors/PCloud` 导致文章页面中点击作者的链接会404。

2021-06-07 10:56 UTC, HEIGE-PCloud reviewed
![Animation](https://user-images.githubusercontent.com/52968553/121005038-46f66f80-c787-11eb-822e-61ae4709e952.gif)

主页上的链接好像全挂了，不知道改了啥，还是我的环境问题？

2021-06-07 14:02 UTC, xqbumu commented on layouts/partials/meta/author.html
> +            <a href='{{ .link }}'>{{- .name -}}</a>
URL 对大小写敏感的，我已经在 layouts/partials/function/authorinfo.html 里加了 lower 了。

2021-06-07 20:37 UTC, HEIGE-PCloud approved these changes
大功告成！

你看看还有没有什么问题，或者需要修改和补充的，然后就可以合并了 😊

2021-06-08 00:11 UTC, xqbumu commented
> 大功告成！
> 
> 你看看还有没有什么问题，或者需要修改和补充的，然后就可以合并了 😊

可以 squash 下后再合并，然后就没什么问题了。

2021-06-08 06:43 UTC, merged